const express=require('express');const cors=require('cors');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');require('dotenv').config();const db=require('./db');const {authRequired}=require('./auth');
const adminRequired=(req,res,next)=>{if(req.user?.role!=='admin')return res.status(403).json({message:'Admin access required.'});next();};
const app=express();app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'}));app.use(express.json());
const secret=()=>process.env.JWT_SECRET||'student_exam_secret_change_me';
app.get('/api/health',async(req,res)=>{try{await db.query('SELECT 1');res.json({ok:true,message:'API and MySQL are connected.'});}catch(e){res.status(500).json({ok:false,message:e.message});}});
app.post('/api/auth/register',async(req,res)=>{try{const {fullName,email,password}=req.body;if(!fullName||!email||!password)return res.status(400).json({message:'Full name, email and password are required.'});if(password.length<6)return res.status(400).json({message:'Password must contain at least 6 characters.'});const [x]=await db.query('SELECT id FROM users WHERE email=?',[email.trim()]);if(x.length)return res.status(409).json({message:'Email already exists.'});const hash=await bcrypt.hash(password,10);const temporaryStudentId=`TMP-${Date.now()}-${Math.floor(Math.random()*100000)}`;const [r]=await db.query('INSERT INTO users(full_name,student_id,email,password_hash) VALUES(?,?,?,?)',[fullName.trim(),temporaryStudentId,email.trim(),hash]);const studentId=`STU${String(r.insertId).padStart(6,'0')}`;await db.query('UPDATE users SET student_id=? WHERE id=?',[studentId,r.insertId]);res.status(201).json({message:`Registration successful. Your Student ID is ${studentId}.`,userId:r.insertId,studentId});}catch(e){console.error(e);res.status(500).json({message:'Registration failed.'});}});
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body;const [rows]=await db.query('SELECT * FROM users WHERE email=?',[email]);if(!rows.length||!(await bcrypt.compare(password,rows[0].password_hash)))return res.status(401).json({message:'Invalid email or password.'});const u=rows[0];const token=jwt.sign({id:u.id,email:u.email,role:u.role},secret(),{expiresIn:'8h'});res.json({token,user:{id:u.id,fullName:u.full_name,studentId:u.student_id,email:u.email,role:u.role}});}catch(e){console.error(e);res.status(500).json({message:'Login failed. Check MySQL configuration.'});}});
app.get('/api/me',authRequired,async(req,res)=>{const [r]=await db.query('SELECT id,full_name,student_id,email,role FROM users WHERE id=?',[req.user.id]);if(!r.length)return res.status(404).json({message:'User not found.'});const u=r[0];res.json({id:u.id,fullName:u.full_name,studentId:u.student_id,email:u.email,role:u.role});});

// ---------------- ADMIN API ----------------
app.post('/api/admin/login',async(req,res)=>{try{const {email,password}=req.body;const [rows]=await db.query("SELECT * FROM users WHERE email=? AND role='admin' LIMIT 1",[email]);if(!rows.length||!(await bcrypt.compare(password,rows[0].password_hash)))return res.status(401).json({message:'Invalid admin credentials.'});const u=rows[0];const token=jwt.sign({id:u.id,email:u.email,role:u.role},secret(),{expiresIn:'8h'});res.json({token,user:{id:u.id,fullName:u.full_name,email:u.email,role:u.role}});}catch(e){console.error(e);res.status(500).json({message:'Admin login failed.'});}});
app.get('/api/admin/overview',authRequired,adminRequired,async(req,res)=>{try{const [[students]]=await db.query("SELECT COUNT(*) count FROM users WHERE role='student'");const [[exams]]=await db.query('SELECT COUNT(*) count FROM exams');const [[questions]]=await db.query('SELECT COUNT(*) count FROM questions');const [[results]]=await db.query('SELECT COUNT(*) count FROM results');const [[contacts]]=await db.query('SELECT COUNT(*) count FROM contact');const [[feedback]]=await db.query('SELECT COUNT(*) count FROM feedback');const [recentResults]=await db.query("SELECT r.id,r.score,r.total_questions,r.percentage,r.submitted_at,u.full_name student,e.title FROM results r JOIN users u ON u.id=r.user_id JOIN exams e ON e.id=r.exam_id ORDER BY r.id DESC LIMIT 6");const [recentContacts]=await db.query('SELECT id,name,email,subject,created_at FROM contact ORDER BY id DESC LIMIT 5');res.json({stats:{students:students.count,exams:exams.count,questions:questions.count,results:results.count,contacts:contacts.count,feedback:feedback.count},recentResults,recentContacts});}catch(e){console.error(e);res.status(500).json({message:'Unable to load admin overview.'});}});
app.get('/api/admin/exams',authRequired,adminRequired,async(req,res)=>{const [rows]=await db.query('SELECT e.*, (SELECT COUNT(*) FROM questions q WHERE q.exam_id=e.id) question_count FROM exams e ORDER BY e.id DESC');res.json(rows);});
app.post('/api/admin/exams',authRequired,adminRequired,async(req,res)=>{try{const {title,subject,duration_minutes,total_questions,description,is_active=true}=req.body;if(!title||!subject)return res.status(400).json({message:'Title and subject are required.'});const [r]=await db.query('INSERT INTO exams(title,subject,duration_minutes,total_questions,description,is_active) VALUES(?,?,?,?,?,?)',[title.trim(),subject.trim(),Number(duration_minutes)||10,Number(total_questions)||0,description?.trim()||'',!!is_active]);res.status(201).json({id:r.insertId,message:'Exam created successfully.'});}catch(e){console.error(e);res.status(500).json({message:'Unable to create exam.'});}});
app.put('/api/admin/exams/:id',authRequired,adminRequired,async(req,res)=>{try{const {title,subject,duration_minutes,total_questions,description,is_active}=req.body;await db.query('UPDATE exams SET title=?,subject=?,duration_minutes=?,total_questions=?,description=?,is_active=? WHERE id=?',[title?.trim(),subject?.trim(),Number(duration_minutes)||10,Number(total_questions)||0,description?.trim()||'',!!is_active,req.params.id]);res.json({message:'Exam updated successfully.'});}catch(e){console.error(e);res.status(500).json({message:'Unable to update exam.'});}});
app.delete('/api/admin/exams/:id',authRequired,adminRequired,async(req,res)=>{try{await db.query('DELETE FROM exams WHERE id=?',[req.params.id]);res.json({message:'Exam deleted successfully.'});}catch(e){console.error(e);res.status(500).json({message:'Unable to delete exam.'});}});
app.get('/api/admin/questions',authRequired,adminRequired,async(req,res)=>{const [rows]=await db.query('SELECT q.*,e.title exam_title FROM questions q JOIN exams e ON e.id=q.exam_id ORDER BY q.id DESC');res.json(rows);});
app.post('/api/admin/questions',authRequired,adminRequired,async(req,res)=>{try{const {exam_id,question_text,option_a,option_b,option_c,option_d,correct_option}=req.body;if(!exam_id||!question_text||!option_a||!option_b||!option_c||!option_d||correct_option===undefined)return res.status(400).json({message:'All question fields are required.'});const [r]=await db.query('INSERT INTO questions(exam_id,question_text,option_a,option_b,option_c,option_d,correct_option) VALUES(?,?,?,?,?,?,?)',[exam_id,question_text.trim(),option_a.trim(),option_b.trim(),option_c.trim(),option_d.trim(),Number(correct_option)]);res.status(201).json({id:r.insertId,message:'Question added successfully.'});}catch(e){console.error(e);res.status(500).json({message:'Unable to add question.'});}});
app.put('/api/admin/questions/:id',authRequired,adminRequired,async(req,res)=>{try{const {exam_id,question_text,option_a,option_b,option_c,option_d,correct_option}=req.body;await db.query('UPDATE questions SET exam_id=?,question_text=?,option_a=?,option_b=?,option_c=?,option_d=?,correct_option=? WHERE id=?',[exam_id,question_text.trim(),option_a.trim(),option_b.trim(),option_c.trim(),option_d.trim(),Number(correct_option),req.params.id]);res.json({message:'Question updated successfully.'});}catch(e){console.error(e);res.status(500).json({message:'Unable to update question.'});}});
app.delete('/api/admin/questions/:id',authRequired,adminRequired,async(req,res)=>{try{await db.query('DELETE FROM questions WHERE id=?',[req.params.id]);res.json({message:'Question deleted successfully.'});}catch(e){console.error(e);res.status(500).json({message:'Unable to delete question.'});}});
app.get('/api/admin/students',authRequired,adminRequired,async(req,res)=>{const [rows]=await db.query("SELECT id,full_name,student_id,email,created_at FROM users WHERE role='student' ORDER BY id DESC");res.json(rows);});
app.delete('/api/admin/students/:id',authRequired,adminRequired,async(req,res)=>{try{await db.query("DELETE FROM users WHERE id=? AND role='student'",[req.params.id]);res.json({message:'Student deleted successfully.'});}catch(e){console.error(e);res.status(500).json({message:'Unable to delete student.'});}});
app.get('/api/admin/results',authRequired,adminRequired,async(req,res)=>{const [rows]=await db.query("SELECT r.id,r.score,r.total_questions,r.percentage,r.submitted_at,u.full_name student,u.student_id,e.title,e.subject FROM results r JOIN users u ON u.id=r.user_id JOIN exams e ON e.id=r.exam_id ORDER BY r.id DESC");res.json(rows);});
app.get('/api/admin/contacts',authRequired,adminRequired,async(req,res)=>{const [rows]=await db.query('SELECT * FROM contact ORDER BY id DESC');res.json(rows);});
app.delete('/api/admin/contacts/:id',authRequired,adminRequired,async(req,res)=>{await db.query('DELETE FROM contact WHERE id=?',[req.params.id]);res.json({message:'Contact message deleted.'});});
app.get('/api/admin/feedback',authRequired,adminRequired,async(req,res)=>{const [rows]=await db.query("SELECT f.*,u.full_name student,u.student_id FROM feedback f JOIN users u ON u.id=f.user_id ORDER BY f.id DESC");res.json(rows);});
app.delete('/api/admin/feedback/:id',authRequired,adminRequired,async(req,res)=>{await db.query('DELETE FROM feedback WHERE id=?',[req.params.id]);res.json({message:'Feedback deleted.'});});

app.get('/api/exams',authRequired,async(req,res)=>{const [r]=await db.query('SELECT id,title,subject,duration_minutes,total_questions,description FROM exams WHERE is_active=1 ORDER BY id');res.json(r);});
app.get('/api/exams/:id',authRequired,async(req,res)=>{const [e]=await db.query('SELECT id,title,subject,duration_minutes,total_questions,description FROM exams WHERE id=? AND is_active=1',[req.params.id]);if(!e.length)return res.status(404).json({message:'Exam not found.'});const [q]=await db.query('SELECT id,question_text,option_a,option_b,option_c,option_d FROM questions WHERE exam_id=? ORDER BY id',[req.params.id]);res.json({...e[0],questions:q.map(x=>({id:x.id,question:x.question_text,options:[x.option_a,x.option_b,x.option_c,x.option_d]}))});});
app.post('/api/exams/:id/submit',authRequired,async(req,res)=>{const conn=await db.getConnection();try{const {answers={},startedAt}=req.body;const [e]=await conn.query('SELECT * FROM exams WHERE id=? AND is_active=1',[req.params.id]);if(!e.length)return res.status(404).json({message:'Exam not found.'});const exam=e[0];const [qs]=await conn.query('SELECT id,correct_option FROM questions WHERE exam_id=? ORDER BY id',[exam.id]);let score=0;const details=qs.map(q=>{const selected=answers[String(q.id)]===undefined?null:Number(answers[String(q.id)]);const correct=selected!==null&&selected===q.correct_option;if(correct)score++;return{questionId:q.id,selectedOption:selected,isCorrect:correct};});const pct=qs.length?score/qs.length*100:0;await conn.beginTransaction();const [r]=await conn.query('INSERT INTO results(user_id,exam_id,score,total_questions,percentage,started_at) VALUES(?,?,?,?,?,?)',[req.user.id,exam.id,score,qs.length,pct,startedAt?new Date(startedAt):null]);for(const d of details)await conn.query('INSERT INTO result_answers(result_id,question_id,selected_option,is_correct) VALUES(?,?,?,?)',[r.insertId,d.questionId,d.selectedOption,d.isCorrect]);await conn.commit();res.json({resultId:r.insertId,score,total:qs.length,percentage:Math.round(pct),details});}catch(err){await conn.rollback();console.error(err);res.status(500).json({message:'Unable to submit examination.'});}finally{conn.release();}});
app.get('/api/results',authRequired,async(req,res)=>{const [r]=await db.query('SELECT r.id,r.score,r.total_questions,r.percentage,r.submitted_at,e.title,e.subject FROM results r JOIN exams e ON e.id=r.exam_id WHERE r.user_id=? ORDER BY r.id DESC',[req.user.id]);res.json(r);});
app.get('/api/results/:id',authRequired,async(req,res)=>{const [r]=await db.query('SELECT r.*,e.title,e.subject FROM results r JOIN exams e ON e.id=r.exam_id WHERE r.id=? AND r.user_id=?',[req.params.id,req.user.id]);if(!r.length)return res.status(404).json({message:'Result not found.'});const [a]=await db.query('SELECT ra.question_id,ra.selected_option,ra.is_correct,q.question_text,q.option_a,q.option_b,q.option_c,q.option_d,q.correct_option FROM result_answers ra JOIN questions q ON q.id=ra.question_id WHERE ra.result_id=? ORDER BY ra.id',[req.params.id]);res.json({...r[0],answers:a});});

app.post('/api/contact',async(req,res)=>{try{const {name,email,subject,message}=req.body;if(!name||!email||!subject||!message)return res.status(400).json({message:'All contact fields are required.'});const [r]=await db.query('INSERT INTO contact(name,email,subject,message) VALUES(?,?,?,?)',[name.trim(),email.trim(),subject.trim(),message.trim()]);res.status(201).json({message:'Your message has been submitted successfully.',id:r.insertId});}catch(e){console.error(e);res.status(500).json({message:'Unable to submit contact form.'});}});
app.post('/api/feedback',authRequired,async(req,res)=>{try{const {rating,category,message}=req.body;if(!rating||!category||!message)return res.status(400).json({message:'Rating, category and feedback are required.'});const ratingNumber=Number(rating);if(ratingNumber<1||ratingNumber>5)return res.status(400).json({message:'Rating must be between 1 and 5.'});const [r]=await db.query('INSERT INTO feedback(user_id,rating,category,message) VALUES(?,?,?,?)',[req.user.id,ratingNumber,category.trim(),message.trim()]);res.status(201).json({message:'Your feedback has been submitted successfully.',id:r.insertId});}catch(e){console.error(e);res.status(500).json({message:'Unable to submit feedback.'});}});

const port=Number(process.env.PORT||5000);app.listen(port,()=>console.log(`API running on http://localhost:${port}`));
